### ISSUE TITLE
Buffer overwrite in SendSysEx()

### ISSUE THREAD

**Issue by MathisRosenhauer** [YuuichiAkagawa/USBH_MIDI#22]
Hi,
I'm using SendSysEx() and noticed that buf gets overwritten during the call to pUsb->outTransfer(). The root cause is SPI.transfer() in the SPI_HAS_TRANSACTION case. Anyway, the solution seems to be to to set

buf[0] = (nCable << 4) | 0x4;

inside the loop because it gets overwritten during each iteration.

Cheers,
Mathis

**Comment by YuuichiAkagawa** [comment]
Thank you for your report.
I confirmed the this issue.
