### ISSUE TITLE
USBH_MIDI_Converter does not work on an Arduino Uno if unplugged from PC

### ISSUE THREAD

**Issue by morduno** [YuuichiAkagawa/USBH_MIDI#36]
Hello,

I am trying to use the USBH_MIDI_Converter example with this setup: an Arduino Uno with a USB Host Shield from SparkFun. The Arduino is powered through the barrel jack, but I also use the Arduino's USB port to upload the sketch.

The USBH_MIDI_Converter example works perfectly when the USB port is connected to my laptop, but as soon as I unplug the USB cable the Arduino becomes erratic and starts sending random things through the MIDI output. The problem is fixed as soon as I plug back in the USB cable to the computer.

Any idea of what could be causing this?

Thanks in advance for your help, I am really stuck on this one.

**Comment by YuuichiAkagawa** [comment]
It is not software errro.
In my Uno + Sparkfun's USB Host Shield is works normally.
Please check your hardware or AC adaptor or cable.

note: We are not recommended Sparkfun USB Host shield.

![sfuhs uno](https://cloud.githubusercontent.com/assets/926923/25949375/4d9fb0ba-3692-11e7-94a2-40eae9e28c7e.jpg)
