### ISSUE TITLE
Add isSysEx() function

### ISSUE THREAD

**Issue by YuuichiAkagawa** [YuuichiAkagawa/USBH_MIDI#37]
https://github.com/felis/USB_Host_Shield_2.0/commit/43f423e15d3b992e692f5e6a627970b9a3492c47#commitcomment-24463241

**Comment by flneto** [comment]
Well!!!!!
Hey Yuuichi , Can I use your project like a Kenton Midi USB Host to control usb devices?

**Comment by YuuichiAkagawa** [comment]
It is up to you. This is only a driver.

**Comment by YuuichiAkagawa** [comment]
Sorry, I don't have Kenton. 
You can convert USB MIDI to Legacy MIDI. But not perfect.

**Comment by flneto** [comment]
It is like iConnectMidi.

I think It works like a host... I Will try As soon as possible.

Thank you again!

**Comment by YuuichiAkagawa** [comment]
Withdraw. 
No implementation required.
