### ISSUE TITLE
change SPI channel

### ISSUE THREAD

**Issue by fotosettore** [YuuichiAkagawa/USBH_MIDI#47]
hi
i'm using a ESP32.
i'd like to install two USB HOST same device --> https://i.ebayimg.com/images/g/UUQAAOSwFyhaF6Pj/s-l1600.jpg

I saw that as default, usbh_midi refers to VSPI (18,19,23,5)
what i must do to use HSPI (14,12,13,15) also, or better more add another SS to use two usb host on same line (VSPI or HSPI) ?

here the code that works fine on VSPI with only one usb host shield

-----------------
```
#include <usbh_midi.h>
USB Usb;
USBH_MIDI  Midi(&Usb);

//****
void setup() 
{
  Serial.begin(115200);
  if (Usb.Init() == -1) 
  {
    Serial.println("USB did not start.");
    while(1);
  }  
  else
  {
    Serial.println("Started USB :-)");
  }

/*
 ---> here i'd need to start another usb host  (ex.  usb_2) 
*/
}

```

i think i must refer to **USB_MIDI_converter_multi.ino** but i did not understand how to connect the pin SS of second usb host,

many thanks for help

**Comment by YuuichiAkagawa** [comment]
SPI is controlled by UHS2. It is not this library.
