### ISSUE TITLE
USBH_MIDI for STM32F4 ?

### ISSUE THREAD

**Issue by MrBlueXav** [YuuichiAkagawa/USBH_MIDI#5]
Great respects for your job ! I wish I had the same MIDI USB host implementation for my STM32F4 Discovery board....
But I'm overwhelmed by USB programming complexity at the moment !
Have you planned to adapt it ?
Best regards
Xavier

PS : I'd like to connect a Korg NanoKontrol on my STM32F4 synth :
http://youtu.be/NJDcqiR5RQg

**Comment by Lauszus** [comment]
This is possible since Oct. 2015: https://github.com/felis/USB_Host_Shield_2.0/pull/178. Please see the following example code as well: https://github.com/Lauszus/Nucleo_F446RE_USBHost.
