### ISSUE TITLE
Running Status - Is there a switch to enable ?

### ISSUE THREAD

**Issue by ADI8421** [YuuichiAkagawa/USBH_MIDI#53]
Is there a switch somewhere (true/false etc) to enable Running Status ? Many thanks

**Comment by YuuichiAkagawa** [comment]
What is switch? Please tell me how to use it.

**Comment by ADI8421** [comment]
My question refers to Midi output 'Running Status' 
The firmware reads 'midi running status' input great. The problem is on the midi output. Running status is disabled, which means every midi message has the status byte included. This just increases the bandwidth requirement, especially with Pitch Wheel and Mod Wheel data.
So my question is: Can 'running status' be enabled with a simple change in the source code ? Many thanks.

**Comment by ADI8421** [comment]
It's OK.  I wrote some code inside the USB_MIDI_converter.ino sketch which takes care of running status problem.
    do {
      if( (size=Midi.RcvData(outBuf)) > 0 ){

// Code goes here to enable Running Status.

        //MIDI Output
        _MIDI_SERIAL_PORT.write(outBuf, size);
      }
    }while(size>0);

**Comment by YuuichiAkagawa** [comment]
Thank you, I understand.
There is no function to handle'Running Status' in this library.
You have to implement it yourself.
