### ISSUE TITLE
Will ESP32 / USB Host Shield Mini setup work without INT pin connected ?

### ISSUE THREAD

**Issue by quangvankts** [YuuichiAkagawa/USBH_MIDI#57]
Hi
Will ESP32 / USB Host Shield Mini setup work without INT pin connected ?
Thanks

**Comment by YuuichiAkagawa** [comment]
I don't know ESP32 platform.

```
  //Workaround for non UHS2.0 Shield
  pinMode(7, OUTPUT);
  digitalWrite(7, HIGH);
```

This workaround is for Arduino UNO + [Sparkfun's UHS](https://www.sparkfun.com/products/9947).
