### ISSUE TITLE
Connect two shields back to back.

### ISSUE THREAD

**Issue by jhsa** [YuuichiAkagawa/USBH_MIDI#66]
Would it be possible to connect two shields to each other via the RX and TX pins, and have both USB Host IN/OUTs? Like this we could probably connect two USB devices (slave).
Thanks, I do apologize if this is a stupid question, but I am a beginner to all this.

**Comment by YuuichiAkagawa** [comment]
This is not issue. And it's not about MIDI. 
Please use [Discussions](https://github.com/YuuichiAkagawa/USBH_MIDI/discussions) as needed..

**Comment by jhsa** [comment]
You are right, and I do apologize, I haven't seen the discussions tab before. Sorry about that , my bad.. I am so sorry.
