### ISSUE TITLE
Help to implement control on Mooer Ge200.

### ISSUE THREAD

**Issue by soulwyx** [YuuichiAkagawa/USBH_MIDI#74]
Since I'm running with SAMD21 Host library, I can't run your example.
I run this with Thesycon USB Descriptor Dumper. (in the end of issue)
What I know at this moment:

**This go to preset 3.**
```
uint8_t preset3[64]={	0x08,0xAA,0x55,0x02,0x00,0xA6,0x02,0x85,0x0D,0x00,0xE0,0x0B,0x00,0x00,0x00,0x00,
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
```

**This go to preset 4.**
```
uint8_t preset4[64]={	0x08,0xAA,0x55,0x02,0x00,0xA6,0x03,0x95,0x2C,0x00,0xE0,0x0B,0x00,0x00,0x00,0x00,
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
```

Using HID Send (https://docs.hhdsoftware.com/dms/advanced-features/usb-monitoring/hid-send.html), I can control Mooer Ge200 using the messages above.

My questions is how to  properly initiate the device and send this message using USBHost library.
Could someone give me any tips or directions?

```
#include <Arduino.h>
#include <usb.h>
#include <usbh_midi.h>

USBHost usb;
USBH_MIDI  midiHostUsb(&usb);

byte i;
uint8_t preset3[64]={	0x08,0xAA,0x55,0x02,0x00,0xA6,0x02,0x85,0x0D,0x00,0xE0,0x0B,0x00,0x00,0x00,0x00,
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
	
	uint8_t preset4[64]={	0x08,0xAA,0x55,0x02,0x00,0xA6,0x03,0x95,0x2C,0x00,0xE0,0x0B,0x00,0x00,0x00,0x00,
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
		0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};

void setup() {
	startDisplay();
	usb.Init();
		
	while(1){
		usb.Task();
		delay(100);
		if(usb.getUsbTaskState() == USB_STATE_RUNNING){
                        midiHostUsb.SendMooerData(preset4);
			delay(1000);
		}
	}
}
```

`uint8_t USBH_MIDI::SendMooerData(uint8_t *dataptr){
	return pUsb->outTransfer(bAddress, 0x81, 0x40, dataptr);
}`

With my code I get rcode=219. (USB_ERROR_EP_NOT_FOUND_IN_TBL)
What I'm missing?

Information for device GE200 (VID=0x0483 PID=0x5703):

*** ERROR: Descriptor has errors! ***

------------------------------
Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x000A
Current configuration value: 0x00
Number of open pipes: 0

------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0200	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x40	bMaxPacketSize0   (64 bytes)
0x0483	idVendor
0x5703	idProduct
0x00C8	bcdDevice
0x01	iManufacturer   "MOOER"
0x02	iProduct        "GE200"
0x03	iSerialNumber   "00000000001A"
0x01	bNumConfigurations

-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x00DE	wTotalLength   (222 bytes)
0x04	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0xFA	bMaxPower      (500 mA)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x01	bInterfaceSubClass   (Audio Control Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface

AC Interface Header Descriptor:
------------------------------
0x0A	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x0100	bcdADC
0x0048	wTotalLength   (72 bytes)
0x02	bInCollection
0x02	baInterfaceNr(1)
0x01	baInterfaceNr(2)

AC Input Terminal Descriptor:
------------------------------
0x0C	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x01	bTerminalID
0x0201	wTerminalType   (Microphone)
0x00	bAssocTerminal
0x02	bNrChannels   (2 channels)
0x0003	wChannelConfig
0x00	iChannelNames
0x00	iTerminal

AC Feature Unit Descriptor:
------------------------------
0x0A	bLength
0x24	bDescriptorType
0x06	bDescriptorSubtype
0x02	bUnitID
0x01	bSourceID
0x01	bControlSize
bmaControls: 
 0x01	Channel(0) - Mute
 0x02	Channel(1) - Volume
 0x02	Channel(2) - Volume
0x00	iFeature

AC Output Terminal Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x03	bDescriptorSubtype
0x03	bTerminalID
0x0101	wTerminalType   (USB Streaming)
0x00	bAssocTerminal
0x02	bSourceID
0x00	iTerminal

AC Input Terminal Descriptor:
------------------------------
0x0C	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x04	bTerminalID
0x0101	wTerminalType   (USB Streaming)
0x00	bAssocTerminal
0x02	bNrChannels   (2 channels)
0x0003	wChannelConfig
0x00	iChannelNames
0x00	iTerminal

AC Feature Unit Descriptor:
------------------------------
0x0A	bLength
0x24	bDescriptorType
0x06	bDescriptorSubtype
0x05	bUnitID
0x04	bSourceID
0x01	bControlSize
bmaControls: 
 0x01	Channel(0) - Mute
 0x02	Channel(1) - Volume
 0x02	Channel(2) - Volume
0x00	iFeature

AC Output Terminal Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x03	bDescriptorSubtype
0x06	bTerminalID
0x0301	wTerminalType   (Speaker)
0x00	bAssocTerminal
0x05	bSourceID
0x00	iTerminal

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x01	bAlternateSetting
0x01	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface

AS Interface Descriptor:
------------------------------
0x07	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x03	bTerminalLink
0x01	bDelay
0x0001	wFormatTag   (PCM)

AS Format Type 1 Descriptor:
------------------------------
0x0B	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x01	bFormatType   (FORMAT_TYPE_1)
0x02	bNrChannels   (2 channels)
0x03	bSubframeSize
0x18	bBitResolution   (24 bits per sample)
0x01	bSamFreqType   (Discrete sampling frequencies)
0x00AC44 	tSamFreq(1)   (44100 Hz)

Endpoint Descriptor (Audio/MIDI 1.0):
------------------------------
0x07	bLength
0x05	bDescriptorType
*** ERROR: Invalid descriptor length 0x07 for Audio/MIDI 1.0 endpoint (9 bytes expected)
Hex dump: 
0x07 0x05 0x82 0x05 0x14 0x01 0x01 

AS Isochronous Data Endpoint Descriptor:
------------------------------
0x07	bLength
0x25	bDescriptorType
0x01	bDescriptorSubtype
0x00	bmAttributes
0x00	bLockDelayUnits   (undefined)
0x0000	wLockDelay

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x02	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x02	bInterfaceNumber
0x01	bAlternateSetting
0x01	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface

AS Interface Descriptor:
------------------------------
0x07	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x04	bTerminalLink
0x01	bDelay
0x0001	wFormatTag   (PCM)

AS Format Type 1 Descriptor:
------------------------------
0x0B	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x01	bFormatType   (FORMAT_TYPE_1)
0x02	bNrChannels   (2 channels)
0x03	bSubframeSize
0x18	bBitResolution   (24 bits per sample)
0x01	bSamFreqType   (Discrete sampling frequencies)
0x00AC44 	tSamFreq(1)   (44100 Hz)

Endpoint Descriptor (Audio/MIDI 1.0):
------------------------------
0x07	bLength
0x05	bDescriptorType
*** ERROR: Invalid descriptor length 0x07 for Audio/MIDI 1.0 endpoint (9 bytes expected)
Hex dump: 
0x07 0x05 0x01 0x05 0x14 0x01 0x01 

AS Isochronous Data Endpoint Descriptor:
------------------------------
0x07	bLength
0x25	bDescriptorType
0x01	bDescriptorSubtype
0x00	bmAttributes
0x00	bLockDelayUnits   (undefined)
0x0000	wLockDelay

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x03	bInterfaceNumber
0x00	bAlternateSetting
0x02	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x00	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0110	bcdHID
0x21	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x001B	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x0A	bInterval         (10 frames)

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x02	bEndpointAddress  (OUT endpoint 2)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x0A	bInterval         (10 frames)

Microsoft OS Descriptor is not available. Error code: 0x0000001F

--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
0x01   0x0409  "MOOER"
0x02   0x0409  "GE200"
0x03   0x0409  "00000000001A"

------------------------------

Connection path for device: 
Controlador Host Compatível com USB xHCI
Root Hub
GE200 (VID=0x0483 PID=0x5703) Port: 2

Running on: Windows 10 or greater (Build Version 19042)

Brought to you by TDD v2.17.0, Feb 23 2021, 14:04:02

**Comment by YuuichiAkagawa** [comment]
The descriptor does not appear to have a MIDI interface.
Does this device support USB MIDI?

**Comment by soulwyx** [comment]
```
uint8_t USBH_MIDI::SendMooerData(uint8_t *dataptr){
	
	
	epInfo[epDataOutIndex].maxPktSize=0x40;
	epInfo[epDataOutIndex].epAddr=0x02;
	epInfo[epDataOutIndex].bmAttribs=0x03;
	

	pUsb->setEpInfoEntry(bAddress, 3, epInfo);
	
	return pUsb->outTransfer(bAddress,epInfo[epDataOutIndex].epAddr, epInfo[epDataOutIndex].maxPktSize, dataptr);
}
```

With this implementation now I'm getting Rcode=8 (USB_ERRORTIMEOUT) from dispatchPkt
What I'm still missing?

**Comment by soulwyx** [comment]
> The descriptor does not appear to have a MIDI interface.
> Does this device support USB MIDI?

No, this device don't. I'm trying to force a message.
I can control on my computer sending the message on my computer.

**Comment by YuuichiAkagawa** [comment]
This library will not work without a USB MIDI device. 
Therefore, no matter how hard you try, you will not be able to send messages.

**Comment by soulwyx** [comment]
> This library will not work without a USB MIDI device.
> Therefore, no matter how hard you try, you will not be able to send messages.

Even if I try to create a new function inside?
Can you suggest me a library to make this happen?

**Comment by YuuichiAkagawa** [comment]
Your device is not MIDI, so modifying this library will not help.
We cannot advise on device-specific matters.
