### ISSUE TITLE
USB_desc giving me wrong/different number of interfaces (Line6 HX Stomp)...

### ISSUE THREAD

**Issue by kempline** [YuuichiAkagawa/USBH_MIDI#75]
... compared to pyusb

Here's the output of USB_desc

`
01
--

Device descriptor: 
Descriptor Length:	12
Descriptor type:	01
USB version:		0200
Device class:		EF
Device Subclass:	02
Device Protocol:	01
Max.packet size:	40
Vendor  ID:		0E41
Product ID:		4246
Revision ID:		0200
Mfg.string index:	01
Prod.string index:	03
Serial number index:	02
Number of conf.:	01
total_length: 32

Configuration descriptor:
Total length:		0020
Num.intf:		01
Conf.value:		01
Conf.string:		00
Attr.:			C0
Max.pwr:		00

Interface descriptor:
Intf.number:		00
Alt.:			00
Endpoints:		02
Intf. Class:		FF
Intf. Subclass:		00
Intf. Protocol:		00
Intf.string:		00

Endpoint descriptor:
Endpoint address:	81
Attr.:			02
Max.pkt size:		0040
Polling interval:	00

Endpoint descriptor:
Endpoint address:	01
Attr.:			02
Max.pkt size:		0040
Polling interval:	00

Addr:1(0.0.1)
`

And here's the output of a python script basically dumping the current configuration:

DEVICE ID 0e41:4246 on Bus 000 Address 003 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x200 USB 2.0
 bDeviceClass           :   0xef Miscellaneous
 bDeviceSubClass        :    0x2
 bDeviceProtocol        :    0x1
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x0e41
 idProduct              : 0x4246
 bcdDevice              :  0x200 Device 2.0
 iManufacturer          :    0x1 LINE 6
 iProduct               :    0x3 HX Stomp
 iSerialNumber          :    0x2    3090436
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 0 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :  0x130 (304 bytes)
   bNumInterfaces       :    0x6
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :    0x0 (0 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
    INTERFACE 1: Audio =====================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x0
     bInterfaceClass    :    0x1 Audio
     bInterfaceSubClass :    0x1
     bInterfaceProtocol :   0x20
     iInterface         :    0x0 
    INTERFACE 2: Audio =====================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x2
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x0
     bInterfaceClass    :    0x1 Audio
     bInterfaceSubClass :    0x2
     bInterfaceProtocol :   0x20
     iInterface         :    0x0 
    INTERFACE 2, 1: Audio ==================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x2
     bAlternateSetting  :    0x1
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x1 Audio
     bInterfaceSubClass :    0x2
     bInterfaceProtocol :   0x20
     iInterface         :    0x0 
      ENDPOINT 0x3: Isochronous OUT ========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x3 OUT
       bmAttributes     :    0x5 Isochronous
       wMaxPacketSize   :   0xe0 (224 bytes)
       bInterval        :    0x1
    INTERFACE 3: Audio =====================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x3
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x0
     bInterfaceClass    :    0x1 Audio
     bInterfaceSubClass :    0x2
     bInterfaceProtocol :   0x20
     iInterface         :    0x0 
    INTERFACE 3, 1: Audio ==================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x3
     bAlternateSetting  :    0x1
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x1 Audio
     bInterfaceSubClass :    0x2
     bInterfaceProtocol :   0x20
     iInterface         :    0x0 
      ENDPOINT 0x83: Isochronous IN ========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :   0x25 Isochronous
       wMaxPacketSize   :   0xe0 (224 bytes)
       bInterval        :    0x1
    INTERFACE 4: Audio =====================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x4
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :    0x1 Audio
     bInterfaceSubClass :    0x3
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x2: Bulk OUT ===============================
       bLength          :    0x9 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x2 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x82: Bulk IN ===============================
       bLength          :    0x9 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x82 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
    INTERFACE 5: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x5
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x84: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x84 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0x8 (8 bytes)
       bInterval        :    0x8

I'd like to use interface 4 for Midi communication but as far as I understand, USB_desc is only detecting one interface. Anything I can do/try?

Thanks in advance
kempline

**Comment by kempline** [comment]
I was not aware of that example but is gives me pretty much the same output:

`
01
--
String Descriptors:
Manufacturer:		LINE 6
Product:		HX Stomp
Serial:			   3090436

Device descriptor: 
Descriptor Length:	12
Descriptor type:	01
USB version:		0200
Device class:		EF
Device Subclass:	02
Device Protocol:	01
Max.packet size:	40
Vendor  ID:		0E41
Product ID:		4246
Revision ID:		0200
Mfg.string index:	01
Prod.string index:	03
Serial number index:	02
Number of conf.:	01

Configuration descriptor:
Total length:		0020
Num.intf:		01
Conf.value:		01
Conf.string:		00
Attr.:			C0
Max.pwr:		00

Interface descriptor:
Intf.number:		00
Alt.:			00
Endpoints:		02
Intf. Class:		FF
Intf. Subclass:		00
Intf. Protocol:		00
Intf.string:		00

Endpoint descriptor:
Endpoint address:	81
Attr.:			02(Bulk)
Max.pkt size:		0040
Polling interval:	00

Endpoint descriptor:
Endpoint address:	01
Attr.:			02(Bulk)
Max.pkt size:		0040
Polling interval:	00


Addr:1(0.0.1)

`

**Comment by YuuichiAkagawa** [comment]
Does the LINE 6 HX Stomp support Full-Speed? USB Host Shield does not support High-Speed.

The contents of the configuration descriptor are different.

USB Host Shiled
```
Configuration descriptor:
Total length: 0020
Num.intf: 01
```
pyusb(PC)
```
CONFIGURATION 1: 0 mA ====================================
wTotalLength : 0x130 (304 bytes)
bNumInterfaces : 0x6
```

**Comment by kempline** [comment]
<img width="512" alt="stomp_usb" src="https://user-images.githubusercontent.com/34777492/136979223-32b4e8b9-01cc-46a9-b96c-6d5d1532d783.png">

Well, that's a very good question. At least it connects as High-Speed Midi device to my laptop. Do you have any idea how I can simulate lower USB speeds? Maybe I can try to find a USB 1.0 hub somewhere - would that be a good test?

**Comment by kempline** [comment]
One of my colleagues found an old USB 1.0 hub and if I connect the LINE 6 HX Stomp thru this hub to my laptop the interface list (see my first posting) gets shortened as:

`
DEVICE ID 0e41:4246 on Bus 001 Address 008 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x200 USB 2.0
 bDeviceClass           :   0xef Miscellaneous
 bDeviceSubClass        :    0x2
 bDeviceProtocol        :    0x1
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x0e41
 idProduct              : 0x4246
 bcdDevice              :  0x200 Device 2.0
 iManufacturer          :    0x1 LINE 6
 iProduct               :    0x3 HX Stomp
 iSerialNumber          :    0x2    3090436
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 0 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :    0x0 (0 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
`
That's pretty much what I get when using the USB Host Shield Library. Thus, I can confirm that it is speed-dependent and that the USB Host Shield Library can't be used to have <Midi over USB> functionality with LINE 6's HX Stomp.

Thanks @YuuichiAkagawa for pointing me to the speed issue. Are you aware of any alternatives? Are there other solutions allowing for high-speed communication using main-stream microcontrollers?

Regards
kempline

**Comment by YuuichiAkagawa** [comment]
Thank you for your report.

Teensy 3.6 & 4.x has a high speed USB Host. But I haven't tried MIDI in high speed mode.
