### ISSUE TITLE
Digital piano not reading data

### ISSUE THREAD

**Issue by Gallinator** [YuuichiAkagawa/USBH_MIDI#78]
Hi, i'm trying to use [this fork](https://github.com/bbx10/USBH_MIDI/tree/due) with an Arduino Due to read midi events from a Yamaha P45 digital piano. The keyboard is correctly recognized, however no midi event can be read. I'm testing with [this example](https://github.com/bbx10/USBH_MIDI/blob/due/examples/USBH_MIDI_dump/USBH_MIDI_dump.ino).
 I tried to see if any midi data was read by using 

     Serial.println(Midi.RecvData( &rcvd,  bufMidi));

and it returns this is the output, which should mean error

     20:32:15.803 -> VID:0499 PID:160F
     20:32:20.805 -> 255
     20:32:25.778 -> 255
     20:32:30.782 -> 255
     20:32:35.788 -> 255

i also tried this to read midi messages

    byte outBuf[3];
    Serial.println(Midi.RecvData(outBuf));

but empty data is received even if i don't press any key

    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0
    20:41:37.474 -> 0

I tried to power the Arduino by using an external power supply and also to modify MIDI_EVENT_PACKET_SIZE and DESC_BUF_SIZE as shown [here](https://github.com/YuuichiAkagawa/USBH_MIDI/issues/52) but with no success.
Here is the result of lsusb on ubuntu

    Bus 001 Device 003: ID 0499:160f Yamaha Corp. P-105
    Couldn't open device, some information will be missing

    Device Descriptor:
    bLength                18
    bDescriptorType         1
    bcdUSB               2.00
    bDeviceClass            0 
    bDeviceSubClass         0 
    bDeviceProtocol         0 
    bMaxPacketSize0        64
    idVendor           0x0499 Yamaha Corp.
    idProduct          0x160f P-105
    bcdDevice            1.00
    iManufacturer           1 Yamaha Corporation
    iProduct                2 Digital Piano
    iSerial                 0 
    bNumConfigurations      1

    Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0065
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower                0mA

    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      1 Control Device
      bInterfaceProtocol      0 
      iInterface              0 

      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      1 (HEADER)
        bcdADC               1.00
        wTotalLength       0x0009
        bInCollection           1
        baInterfaceNr(0)        1

       Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         1 Audio
      bInterfaceSubClass      3 MIDI Streaming
      bInterfaceProtocol      0 
      iInterface              0 

      MIDIStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (HEADER)
        bcdADC               1.00
        wTotalLength       0x0041

      MIDIStreaming Interface Descriptor:
        bLength                 6
        bDescriptorType        36
        bDescriptorSubtype      2 (MIDI_IN_JACK)
        bJackType               2 External
        bJackID                 1
        iJack                   0 

      MIDIStreaming Interface Descriptor:
        bLength                 6
        bDescriptorType        36
        bDescriptorSubtype      2 (MIDI_IN_JACK)
        bJackType               1 Embedded
        bJackID                33
        iJack                   0 

      MIDIStreaming Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (MIDI_OUT_JACK)
        bJackType               2 External
        bJackID                65
        bNrInputPins            1
        baSourceID( 0)         33
        BaSourcePin( 0)         1
        iJack                   0 

      MIDIStreaming Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (MIDI_OUT_JACK)
        bJackType               1 Embedded
        bJackID                97
        bNrInputPins            1
        baSourceID( 0)          1
        BaSourcePin( 0)         1
        iJack                   0 

      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
        bRefresh                0
        bSynchAddress           0
        MIDIStreaming Endpoint Descriptor:
          bLength                 5
          bDescriptorType        37
          bDescriptorSubtype      1 (GENERAL)
          bNumEmbMIDIJack         1
          baAssocJackID( 0)      33

      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
        bRefresh                0
        bSynchAddress           0
        MIDIStreaming Endpoint Descriptor:
          bLength                 5
          bDescriptorType        37
          bDescriptorSubtype      1 (GENERAL)
          bNumEmbMIDIJack         1
          baAssocJackID( 0)      97

 I know that this isn't your project but i hope you can help me

**Comment by YuuichiAkagawa** [comment]
I don't know about forked code.
Please contact the author.
